name: kanriya
version: '3.8'
services:
  db:
    image: postgres:17
    #restart: unless-stopped
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    ports:
      - "10005:5432"
    networks:
      - postgres-network
  pgadmin:
    image: dpage/pgadmin4
    #restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "10004:80"
    depends_on:
      - db
    networks:
      - postgres-network
  
  seq:
    image: datalust/seq:latest
    #restart: unless-stopped
    environment:
      - ACCEPT_EULA=Y
      # Optional: Set an admin password (remove for no auth)
      - SEQ_FIRSTRUN_ADMINPASSWORD=admin123
    ports:
      - "10003:80"     # Web UI
      - "10002:5341"    # Ingestion API
    volumes:
      - ./data/seq:/data
    networks:
      - postgres-network

networks:
  postgres-network:
    driver: bridge