// <auto-generated />
using System;
using Kanriya.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Kanriya.Server.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250822233839_InitialCreate_SnakeCase")]
    partial class InitialCreate_SnakeCase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Kanriya.Server.Data.GreetLog", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("id")
                        .HasComment("Unique identifier for the greet log entry");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("content")
                        .HasComment("The greeting message content");

                    b.Property<DateTime>("Timestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP")
                        .HasComment("UTC timestamp when the greeting was logged");

                    b.HasKey("Id")
                        .HasName("pk_greet_logs");

                    b.HasIndex("Timestamp")
                        .IsDescending()
                        .HasDatabaseName("IX_greet_logs_timestamp");

                    b.ToTable("greet_logs", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
